### ISSUE TITLE
Play game: train IA for given player and submit IA model

### ISSUE THREAD

**Issue by sinedied** [sinedied/skiml#2]
**Tasks:**
- [ ] instanciate game with a time limit
- [ ] during gameplay, feed in/out results to IA engine (try brain.js in streaming mode?)
- [ ] after time limit is exhausted submit result to game server: use submit form built in #4
