### ISSUE TITLE
Play game: use specified IA to get score/rank (on server)

### ISSUE THREAD

**Issue by sinedied** [sinedied/skiml#3]
**Tasks:**
- [ ] Instanciate a game plugged to a specified IA model (generated in #2 )
- [ ] Let the IA play until the player crash (into a rock, tree, etc)
- [ ] submit score (= distance) to server, associated with user

For an equitable ranking, multiple solutions can be considered:
- [ ] Let a given IA (= user) play a specific number of time (5?) then submit the average (simple solution)
or
- [ ] Rank IA by letting them compare 2 by 2 using a ranking system similar to codingame (TrueSkill?)
