### ISSUE TITLE
Create server to submit score and get ranking

### ISSUE THREAD

**Issue by sinedied** [sinedied/skiml#5]
**Tasks:**
- [x] Bootstrap a new (NodeJS/express?) server (I suggest https://feathersjs.com using its generator and default file DB with REST+websockets services)
- [x] Create a new endpoint for submitting score: `POST /scores` (used by #3 )
- [ ] Create a new endpoint to get rankings: `GET /rankings` (ordered array of user + mean score/skill value)
- [ ] Create an endpoint to submit a new IA model `POST /models` (user info + IA model, unique by user name (and also match email) but can be overwritten with new submissions)
- [ ] Spawn matches in dedicated process (or in other CLI tool?) to rank user (if solution 2 of #3 for ranking is used) continuously to update rankings
